# Generated by Django 5.1.2 on 2024-11-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_hotel_reservation_alter_appuser_user_type_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(default='Available', max_length=200),
        ),
    ]
