# Generated by Django 5.1.2 on 2024-11-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_floor_room_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='floor_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
