# Generated by Django 5.1.2 on 2024-11-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_floor_floor_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(default='standard', max_length=200),
        ),
    ]
