# Generated by Django 5.1.2 on 2024-11-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_hotel_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='description',
            field=models.TextField(default='Opis nie został jeszcze wprowadzony.'),
        ),
    ]
