# Generated by Django 5.1.2 on 2024-11-13 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='room_floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_floor', to='users.room'),
        ),
    ]
