# Generated by Django 5.1.2 on 2024-11-15 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_rename_payment_date_payment_payment_creation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='liked_hotels',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.hotel'),
        ),
    ]
