# Generated by Django 5.1.2 on 2024-11-29 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_review_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='recepcionist_hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recepcionist_hotel', to='users.hotel'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='liked_hotels',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liked_hotels', to='users.hotel'),
        ),
    ]
