# Generated by Django 5.1.2 on 2024-11-29 00:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_remove_appuser_liked_hotels_appuser_liked_hotels'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='creation_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2024, 11, 29, 1, 45, 8, 912691)),
            preserve_default=False,
        ),
    ]
