# Generated by Django 5.1.2 on 2024-12-24 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_reservation_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='liked_hotels',
            field=models.ManyToManyField(blank=True, related_name='liked_hotels', to='users.hotel'),
        ),
    ]
