# Generated by Django 5.1.2 on 2024-12-24 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_room_custom_alter_appuser_liked_hotels'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='defaultPrices',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
