# Generated by Django 5.1.2 on 2025-01-05 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_room_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, default='standard_image.png', null=True, upload_to=''),
        ),
    ]
