# Generated by Django 5.1.2 on 2025-01-05 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_room_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(default='standard_image.png', upload_to=''),
        ),
    ]
