# Generated by Django 5.1.2 on 2025-01-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_alter_appuser_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='costs',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='earnings',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
