# Generated by Django 5.1.2 on 2025-01-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_hotel_deposit_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='email',
            field=models.CharField(default='weles@gmail.com', max_length=1000),
        ),
    ]
