# Generated by Django 5.1.2 on 2025-01-10 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_hotel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='phone',
            field=models.CharField(default='+48 123 456 789', max_length=15),
        ),
    ]
