# Generated by Django 5.1.2 on 2025-01-11 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_alter_hotel_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='optional_guest_data',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
