# Generated by Django 5.1.2 on 2025-01-11 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_reservation_optional_guest_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='additions',
            field=models.JSONField(blank=True, default={'breakfast': False, 'parking': False, 'wifi': True}, null=True),
        ),
    ]
