# Generated by Django 5.1.2 on 2025-01-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_reservation_additions'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='deposit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=100, null=True),
        ),
    ]
